#!/bin/bash
#Rename mp3 files using their id3 tags

for i in "$1"{.,}*;

do

artist="$(id3v2 -l "$i" | grep TPE1 | cut -c 38-)"

album="$(id3v2 -l "$i" | grep TALB | cut -c 32-)"

title="$(id3v2 -l "$i" | grep TIT2 | cut -c 44-)"


#echo $artist

#echo $album

#echo $title

mv "$i" "$1/$artist - $album - $title.mp3"

echo "$i RENAMED TO: $artist - $album - $title.mp3";

done
